### PR TITLE
Add method to receive message and store it to json file

### PR DESCRIPTION
**Pull request by bayucakra20**
### What have you Changed -
Adding new method called `receive_messages` in notifly.py

### Issue no.(must) -
#7 

### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me
- [x] One Change in one Pull Request
- [ ] My file is in proper folder
- [ ] I am following clean code and Documentation.
- [ ] I have added README.md with my script

### CODE REVIEW

**Comment by rexdivakar** [comment]
Hey @bayucakra20  have u tested the changes ?

**Comment by bayucakra20** [comment]
Yes i have rexdivakar , let me add the unit test if you want

**Comment by rexdivakar** [comment]
Please add the test cases, also i have found some issues with ur code, can u please correct them !!

**Review by rexdivakar — CHANGES_REQUESTED** [review]
1. Please refactor the code as per flake-8 standards 
2. I find that ur code needs .json file to be present if not it will fail- please correct it in a manner that if the messages.json not present it will automatically create the file and append it 
3. Place the json file under a folder message/conversation.json

**Comment by rexdivakar** [comment]
Are u still working on this issue ? @bayucakra20

**Comment by bayucakra20** [comment]
Hi @rexdivakar , yes I'm still working on this, have been busy with my job this week, will continue tomorrow

**Comment by bayucakra20** [comment]
Hi @rexdivakar , I have updated the PR, kindly review it again

**Comment by rexdivakar** [comment]
Closing #22  due to inactivity

**Pull request closed without merging**
