### PR TITLE
created the issue template

### PR DESCRIPTION
**Pull request by Sloth-Panda**
the issue it corresponds to -> #41 
created the issue template that consists of a feature, bug, and documentation template

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
@rexdivakar  can you please check out the pr?

**Review by rexdivakar — APPROVED** [review]

**Comment by Sloth-Panda** [comment]
@rexdivakar  can you please add dwoc  and level-2 tags to it else it won't be counted so

**Comment by rexdivakar** [comment]
This is an easy job buddy cant give u credits to level-2. Hope you are satisfied 💯

**Comment by Sloth-Panda** [comment]
@rexdivakar  no issue just wanted the tags to be added

**Pull request merged**
