### PR TITLE
Progress Bar 

### PR DESCRIPTION
**Pull request by Kirkkm**
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [ ] I have added README.md with my script

### CODE REVIEW

**Comment by Kirkkm** [comment]
@rexdivakar I am not understanding the commit conflict reported here, is there something I need to fix & fix on my side?

**Comment by rexdivakar** [comment]
Hey @Kirkkm  Please update the fork and add in your changes, also support ur changes with screenshots !

**Comment by Kirkkm** [comment]
> 
> 
> Hey @Kirkkm Please update the fork and add in your changes, also support ur changes with screenshots !

Sounds good, will do.

**Comment by Kirkkm** [comment]
@rexdivakar I updated my fork and added back my changes for the progress bar, also below is a screen shot of the progress bar in action.

progressbar_Screenshot

**Comment by rexdivakar** [comment]
Hey buddy @Kirkkm 

The issue is TQDM is not showing the output scale during transmission, I need a progress bar which shows live movement of data during transmission


image

**Comment by Kirkkm** [comment]
> 
> 
> Hey buddy @Kirkkm
> 
> The issue is TQDM is not showing the output scale during transmission, I need a progress bar which shows live movement of data during transmission
> 
> image

@rexdivakar Ok, I will continue to work on it

**Comment by Kirkkm** [comment]
@rexdivakar, not sure what I did but I am not ready to send another pull request yet. please ignore above message.

**Comment by rexdivakar** [comment]
Closing your PR @Kirkkm  Thanks for ur effort

**Comment by Kirkkm** [comment]
@rexdivakar no problem, will have a new PR ready hopefully here soon for the upload progress bar

**Comment by rexdivakar** [comment]
Oh then i will reassign the issue to u, take ur time happy to have ur contribution and will share my insights about it soon @Kirkkm

**Comment by Kirkkm** [comment]
@rexdivakar Yeah no worries, this is a interesting problem/feature to add and hopefully the solution I am developing will be good but if not would like to collaborate on a better solution.

**Pull request closed without merging**
