### PR TITLE
Upload progress bar

### PR DESCRIPTION
**Pull request by Kirkkm**
#### More Details:
In my research I was unable to find a way to check the progress of the data being transferred in a HTTP Post request, but read online that the best way to approach this was to read each file to be sent, use that iteration to create a progress bar, then send the data in the HTTP Post request.

If you would like further explanation please reach out to me via discord (Kirkkm#7775)

#### Screenshot

image

### Self Check(Tick After Making pull Request)

- [x] Add ScreenShot show casing your work
- [x] One Change in one Pull Request
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [ ] I have added README.md with my script

### Programming Language

- [x] Python

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

#### Sanchit -- Discord id (sanchit#5988)

Discord server  - https://discord.gg/e47wmTW

Happy Coding,

### CODE REVIEW

**Comment by rexdivakar** [comment]
Great job buddy @Kirkkm  But is it possible to optimize the speed cox its taking too long to transmit the data !!

**Comment by Kirkkm** [comment]
> 
> 
> Great job buddy @Kirkkm But is it possible to optimize the speed cox its taking too long to transmit the data !!

@rexdivakar I think I can, what size file were you testing with? (want to make sure I can see what you are seeing)

**Comment by rexdivakar** [comment]
I tried a 30mb file size and it still running, i do recognize this process takes high CPU Usage so we need to optimize it else it might be a major performance issue during realtime run,

Let me know if u need anything
Divakar -- Discord id (root#5998)
Sanchit -- Discord id (sanchit#5988)
Discord server - https://discord.gg/e47wmTW


image

**Comment by rexdivakar** [comment]
Also @Kirkkm  As per ur code initially ur parsing the file that's the reason its using high CPU and sending the file at the last but it has to be done in real time and that's the reason this process is slow. We need a way to change it

**Comment by Kirkkm** [comment]
> 
> 
> Also @Kirkkm As per ur code initially ur parsing the file that's the reason its using high CPU and sending the file at the last but it has to be done in real time and that's the reason this process is slow. We need a way to change it

@rexdivakar hmm... ok I may have a few things I can try to speed it up.

**Comment by Kirkkm** [comment]
@rexdivakar I updated the code to run faster reading in the files and you can set how fast it runs as well.

**Pull request closed without merging**
