### PR TITLE
Updated readme 

### PR DESCRIPTION
**Pull request by Sloth-Panda**
corresponds to issue -> #42

### CODE REVIEW

**Comment by rexdivakar** [comment]
Hey, @Sloth-Panda I feel this is too bloated can come up with something else ??

@SanchitJain123  did u mean anything like this ?

**Comment by Sloth-Panda** [comment]
@rexdivakar  do u mean do u want images a little smaller?

**Comment by SanchitJain123** [comment]
Actually, I was expecting gifs for the functionalities example that are given in readme, not the memes. Like we can show gif that how sending telegram message works.

**Comment by Sloth-Panda** [comment]
What changes you require then

**Comment by rexdivakar** [comment]
Please create a gif demonstrating the usage of the package !! i.e How it works and triggers the setup to notify !

**Comment by Sloth-Panda** [comment]
I am not so sure how i can create those gifs, so i guess if you dont like the other included gifs then i should remove them and make a pr again and let the open-source section be there??

**Comment by rexdivakar** [comment]
We are looking for an appropriate workflow design !! It should be elegant and more informative

**Comment by Sloth-Panda** [comment]
@ I understand that and i am not able to find any gifs that explains what ur project is basically doing, that should not be an issue as these are just gifs and you have your content already explained so let  me know if you want to remove those other gifs that i put or not?

**Comment by SanchitJain123** [comment]
> @ I understand that and i am not able to find any gifs that explains what ur project is basically doing, that should not be an issue as these are just gifs and you have your content already explained so let me know if you want to remove those other gifs that i put or not?

Yes but the point of this PR was to add gifs for the same, please remove this PR otherwise

**Comment by Sloth-Panda** [comment]
Should i remove the issue? In the same issue I have mentioned to add open-source program section and have added that, it was not just for gifs?

**Comment by rexdivakar** [comment]
The issues template is already updated! and we require working model gif, not this kind so we cant approve this change

**Pull request closed without merging**
