### PR TITLE
Added config file for Welcome BOT and Added Issue Templates

### PR DESCRIPTION
**Pull request by muthuannamalai12**
I have added a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time. I have also added an issue template for your repository. This template has four issues namely bug, documentation, feature, proposal.

### CODE REVIEW

**Comment by rexdivakar** [comment]
Can u pls add the server login link https://discord.gg/tTJQxvSaDP
@muthuannamalai12

**Comment by muthuannamalai12** [comment]
> Can u pls add the server login link https://discord.gg/tTJQxvSaDP
> @muthuannamalai12 

I will do it

**Comment by muthuannamalai12** [comment]
> Can u pls add the server login link https://discord.gg/tTJQxvSaDP
> @muthuannamalai12

I have changed it. Kindly review it again @rexdivakar

**Review by rexdivakar — APPROVED** [review]

**Comment by muthuannamalai12** [comment]
@rexdivakar Can you please add DWOC label and the level label on my pull request

**Comment by muthuannamalai12** [comment]
Thank you for adding the labels

**Comment by muthuannamalai12** [comment]
@rexdivakar Can you also add level label like Level 1 issue or level 2 issue as it would be helpful

**Comment by rexdivakar** [comment]
Whats Level 1, Level 2 ??

**Comment by muthuannamalai12** [comment]
@rexdivakar Can I delete the issue template present in workflows which I have placed mistakenly.

**Comment by muthuannamalai12** [comment]
@rexdivakar Can I revert this PR and delete the issue template present in workflow which I have kept mistakenly

**Comment by rexdivakar** [comment]
Yeah i had a feeling it was not working !! @muthuannamalai12

**Comment by muthuannamalai12** [comment]
> Yeah i had a feeling it was not working !! @muthuannamalai12

I have reverted back and created a new pull request. To make sure welcome bot work make sure you install it in your own repo from here https://github.com/apps/welcome

**Comment by muthuannamalai12** [comment]
> @rexdivakar Can you also add level label like Level 1 issue or level 2 issue as it would be helpful

Can you please add me the level labels @rexdivakar

**Comment by rexdivakar** [comment]
I'm sorry I believe we cant do it since the issue isn't been resolved!! Kindly fix it and we shall have u tagged @muthuannamalai12

**Comment by muthuannamalai12** [comment]
> I'm sorry I believe we cant do it since the issue isn't been resolved!! Kindly fix it and we shall have u tagged @muthuannamalai12

Ok I will fix it.

**Comment by muthuannamalai12** [comment]
I have created a pull request again.Kindly review it @rexdivakar

**Comment by rexdivakar** [comment]
image
They look great, nice job @muthuannamalai12

**Comment by muthuannamalai12** [comment]
> image
> They look great, nice job @muthuannamalai12

@rexdivakar Can you please add level labels now

**Comment by muthuannamalai12** [comment]
@rexdivakar Can you please add level labels now

**Pull request merged**
